#ifndef _SW_AHCI_PLATFORM_H
#define _SW_AHCI_PLATFORM_H

#define SW_AHCI_BISTAFR_OFFSET		0x00A0
#define SW_AHCI_BISTCR_OFFSET		0x00A4
#define SW_AHCI_BISTFCTR_OFFSET		0x00A8
#define SW_AHCI_BISTSR_OFFSET		0x00AC
#define SW_AHCI_BISTDECR_OFFSET		0x00B0
#define SW_AHCI_DIAGNR_OFFSET		0x00B4
#define SW_AHCI_DIAGNR1_OFFSET		0x00B8
#define SW_AHCI_OOBR_OFFSET			0x00BC
#define SW_AHCI_PHYCS0R_OFFSET		0x00C0
#define SW_AHCI_PHYCS1R_OFFSET		0x00C4
#define SW_AHCI_PHYCS2R_OFFSET		0x00C8
#define SW_AHCI_TIMER1MS_OFFSET		0x00E0
#define SW_AHCI_GPARAM1R_OFFSET		0x00E8
#define SW_AHCI_GPARAM2R_OFFSET		0x00EC
#define SW_AHCI_PPARAMR_OFFSET		0x00F0
#define SW_AHCI_TESTR_OFFSET		0x00F4
#define SW_AHCI_VERSIONR_OFFSET		0x00F8
#define SW_AHCI_IDR_OFFSET			0x00FC
#define SW_AHCI_RWCR_OFFSET			0x00FC

#endif /* _SW_AHCI_PLATFORM_H */
